package com.rapidphotoflow.domain;

public enum EventType {
    // Photo events
    PHOTO_CREATED,
    PROCESSING_STARTED,
    PROCESSING_COMPLETED,
    PROCESSING_FAILED,
    APPROVED,
    REJECTED,
    DELETED,
    RETRY_REQUESTED,
    TAG_ADDED,
    TAG_REMOVED,
    AUTO_TAGGED,

    // Folder events
    FOLDER_CREATED,
    FOLDER_RENAMED,
    FOLDER_MOVED,
    FOLDER_DELETED,
    PHOTO_MOVED_TO_FOLDER,

    // Album events
    ALBUM_CREATED,
    ALBUM_UPDATED,
    ALBUM_DELETED,
    PHOTO_ADDED_TO_ALBUM,
    PHOTO_REMOVED_FROM_ALBUM
}
